---
- hosts: all
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
    become: true
  - name: Install packeges apt-transport-https
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - openjdk-8-jdk
